### ISSUE TITLE
Gemfile is not working

### ISSUE THREAD

**Issue by tarr1124** [roma/roma#39]
I tried `bundle install` on roma directory but I faced error during tokyocabinet installation.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rbenv/versions/2.1.5/bin/ruby extconf.rb
setting variables ...
  $CFLAGS = -I. -I/usr/local/include -Wall $(cflags) -O2
  $LDFLAGS = -L. -L/usr/local/rbenv/versions/2.1.5/lib  -fstack-protector -rdynamic -Wl,-export-dynamic -L. -L/usr/local/lib
  $libs =  -ltokyocabinet -lz -lbz2 -lpthread -lm -lc
checking for tcutil.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rbenv/versions/2.1.5/bin/ruby
        --with-tokyocabinet-dir
        --without-tokyocabinet-dir
        --with-tokyocabinet-include
        --without-tokyocabinet-include=${tokyocabinet-dir}/include
        --with-tokyocabinet-lib
        --without-tokyocabinet-lib=${tokyocabinet-dir}/lib
/usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
        from extconf.rb:28:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/roma/roma_git_master/.tarrtest/ruby/2.1.0/bundler/gems/tokyocabinet-ruby-1904c4785b45 for inspection.
Results logged to /usr/local/roma/roma_git_master/.tarrtest/ruby/2.1.0/bundler/gems/extensions/x86_64-linux/2.1.0-static/tokyocabinet-ruby-1904c4785b45/gem_make.out
An error occurred while installing tokyocabinet (1.31.a), and Bundler cannot continue.
```

**Comment by satoryu** [comment]
This is not bundler issue but tokyocabinet's one. 
The log says that your system doesn't have libs required for compiling tokyocabinet. 
If you are installing to OS X and have homebrew, do `brew install tokyocabinet` then try `bundle install` again.

**Comment by Matsue** [comment]
:+1:  `brew install tokyo-cabinet`

In my opinion we should move Tokyo Cabinet to roma.gemspec from Gemfile as a development dependency as same as other storages because user can run ROMA without Tokyo Cabinet.

**Comment by satoryu** [comment]
Is this good opportunity to reconsider how storages should be managed.  
In the current implementation, an user has to install tokyo-cabinet even if the user won't use `TCStorage`.  

So I propose splitting some storages as rubygems from roma and allows users to set a storage class to `STORAGE_CLASS = :tc_storage` instead of `STORAGE_CLASS = Roma::Storage::RubyHashStorage`.

**Comment by satoryu** [comment]
This ticket looks able to be closed. how about @tarr1124 ?

**Comment by tarr1124** [comment]
Yes, it was closed. Thank you for your notice @satoryu !

**Comment by satoryu** [comment]
:+1:
